package com.yyh;
import java.util.*;
/*
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class FindTheDifference {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		FindTheDifference mySol = new FindTheDifference();
		System.out.println(mySol.findTheDifference("abcd", "abcde"));
	}

	public char findTheDifference(String s, String t) {
        Map<Character, Integer> a = new HashMap<>();
        for (int i = 0; i < s.length(); i++){
            Integer val = a.get(s.charAt(i));
            if (val == null){
            	a.put(s.charAt(i), 1);
            } else {
            	a.put(s.charAt(i), val+1);
            }
        }
        for (int i = 0; i < t.length(); i++){
        	Integer val = a.get(t.charAt(i));
            if (val == null){
            	return t.charAt(i);
            } else if (val == 1){
            	a.remove(t.charAt(i));
            } else {
            	a.put(t.charAt(i), val - 1);
            }
        }
        return ' ';
    }
}
